name: test

on:
  - push
  - pull_request

jobs:
  before:
    runs-on: ubuntu-latest
    outputs:
      skip-ci: ${{ contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Dummy step
        run: /bin/true

  test:
    runs-on: ${{ matrix.os }}
    needs: before
    if: ${{ !needs.before.outputs.skip_ci }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macOS-latest # no devel-compiler of mac
          # - windows-latest # FIXME
        nim_version:
          - stable
          - devel
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache choosenim
        uses: actions/cache@v3
        with:
          path: ~/.choosenim
          key: ${{ matrix.os }}-choosenim-${{ matrix.nim_version }}-${{ github.run_id }}
          restore-keys: |
            ${{ matrix.os }}-choosenim-${{ matrix.nim_version }}-
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim_version }}
      - name: Test
        run: make V=1 -j $(nproc)
        env:
          DIFF: diff -u
